---
- hosts: all
  tasks:
  - name: Installing OpenVPN
    apt: name=openvpn state=present update_cache=yes
  - name: Installing Easy-RSA
    apt: name=easy-rsa state=present update_cache=yes
  - name: Copying Easy-RSA config to OpenVPN dir
    copy: src=/usr/share/easy-rsa/ dest=/etc/openvpn/easy-rsa
  - name: Creating key vars
    template: src=templates/key-vars.env.j2 dest=/etc/openvpn/easy-rsa/key-vars.env
  - name: Sourcing key vars
    lineinfile: dest=/etc/openvpn/easy-rsa/vars state=present line="source key-vars.env"
  - name: Fixing Easy-RSA script permissions
    file: path="/etc/openvpn/easy-rsa/{{ item }}" mode="u+x"
    with_items:
      - whichopensslcnf
      - clean-all
      - build-ca
      - pkitool
      - build-key-server
      - build-dh
      - build-key
  - name: Patching OpenSSL config to remediate bug
    patch: src=files/openssl-1.0.0.cnf.patch dest=/etc/openvpn/easy-rsa/openssl-1.0.0.cnf
  - name: Setting up CA
    shell: files/setup-ca.sh server
  - name: Copy certificates and keys to OpenVPN
    copy: src=/etc/openvpn/easy-rsa/keys/{{ item }} dest=/etc/openvpn/{{ item }}
    with_items:
      - server.crt
      - server.key
      - ca.crt
      - dh2048.pem
  - name: Take example server config file
    shell: gunzip -c /usr/share/doc/openvpn/examples/sample-config-files/server.conf.gz | tee /etc/openvpn/server.conf
  - name: Use 2048 bit Diffie-Hellman key
    lineinfile: line="dh dh2048.pem" dest=/etc/openvpn/server.conf state=present regexp="^dh dh1024"
  - name: Enable IP forwarding
    lineinfile: line="net.ipv4.ip_forward=1" dest=/etc/sysctl.conf state=present regexp="^#net.ipv4.ip_forward=1"
  - name: Set OpenVPN server user
    lineinfile: line="user nobody" dest=/etc/openvpn/server.conf state=present regexp="^;user nobody"
  - name: Set OpenVPN server group
    lineinfile: line="group nogroup" dest=/etc/openvpn/server.conf state=present regexp="^;group nogroup"
