---
- name: Disable SSH password authentication
  lineinfile: line="PasswordAuthentication no" dest="/etc/ssh/sshd_config" regexp="^#PasswordAuthentication yes" state=present
- name: Set up firewall rules in order
  shell: "iptables {{ item }}"
  with_items:
    - "-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT" # Leave established connections alone
    - "-A INPUT -i lo -j ACCEPT"                              # Stay out of the way of lo
    - "-A OUTPUT -o lo -j ACCEPT"                             # Stay out of the way of lo
    - "-A INPUT -p tcp --tcp-flags ALL NONE -j DROP"          # Drop all null packets
    - "-A INPUT -p tcp --tcp-flags ALL ALL -j DROP"           # Drop X-mas tree packets
    - "-A INPUT -f -j DROP"                                   # Drop fragmented packets
    - "-A INPUT -p tcp ! --syn -m state --state NEW -j DROP"  # Force SYN check for new connections
    - "-A INPUT -i eth0 -p udp --dport 1194 -j ACCEPT"        # Accept OpenVPN connections on the public network interface
    - "-A INPUT -i tun0 -p tcp --dport 22 -j ACCEPT"          # Accept SSH connections on private network interface
    - "-P INPUT DROP"
    - "-A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT" # Leave established forward connections alone
    - "-A FORWARD -s 10.8.0.0/24 -j ACCEPT"                   # Accept packets to be forwarded when they come from the VPN network
    - "-P FORWARD DROP"
  notify: Persist iptables config
